### ISSUE TITLE
[Order cycles] Display "coordinator" column in the OC list for producer profiles

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#313] opened 2022-10-26 10:53 UTC
## What is the need / problem?
In the OC list page (admin/order_cycles), if a shop is a profile, the column "coordinator" is not displayed.
As very often OC names are not helping to know which shop it corresponds to, this forces users to enter in the detail of an order cycle to know which shop it regards (there's the coordinator name displayed at step1).

**OC list view for producer profile:**
![Screen Shot 2022-10-26 at 12 36 10](https://user-images.githubusercontent.com/28386648/198007920-3208ece9-59a8-4c81-9cb3-4ef9c565034d.png)

**OC list view for shops:**
![Screen Shot 2022-10-26 at 12 38 03](https://user-images.githubusercontent.com/28386648/198007988-b530806a-6b73-4569-872e-f4c505b1011c.png)

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Adding the "coordinator" column when an enterprise is a profile, as it is for other enterprises.

**Comment by RachL** [comment] 2023-01-04 10:30
So the column is already selectable in the column button: we need to understand why the columns does not show for producers: bug or complex feature? the spike is a papercut

**Comment by RachL** [comment] 2023-01-13 15:26
hmmmm while preparing the issue I actually could display the coordinator columns without any problem. @filipefurtad0 I think you have managed to reproduce? Can you share your credentials?

**Comment by filipefurtad0** [comment] 2023-01-13 16:46
> I actually could display the coordinator columns without any problem as produce profile only. 

I can observe this @RachL when logging in as a producer only profile, which is supplying an order cycle. You can check it out logging into staging-UK with:
- user `fi.........do+kimchip@gmail.com` (replacing `fi.........do` with my first and last name)
- pass `kimchip123`.

**Comment by RachL** [comment] 2023-01-13 17:08
ok indeed thanks @filipefurtad0 It's the same for producer shop actually. I think it answer part of the spike: the column display works IF the producer shop or profile is coordinating the OC. So it looks like it was made on purpose? but then I don't understand why we would display the info in the edit option.

Let's see with the spike :+1:

**Comment by RachL** [comment] 2023-03-24 10:20
Created https://github.com/openfoodfoundation/openfoodnetwork/issues/10611 closing here

**Closed by RachL** 2023-03-24 10:20 UTC
Labels: blocked, Confirmed Papercut
