### ISSUE TITLE
Historical Orders requiring Authorisation in customer account

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/wishlist#5] opened 2021-03-17 13:21 UTC
## Description

Visit customer account user id 200213 a number of transactions are listed under /transactions as requiring 'Authorisation'

Date range of these historical transactions is from Nov 2019 to Nov 2020.

All transactions are complete and none used the Stripe SCA payment method.

Only unauthorised transactions should appear under the heading 'Authorisation Required' in this tab.

Customer needs to have confidence in data recorded in their account to authenicate a payment that really does require SCA authorisation.

## Expected Behavior

Only transactions requiring SCA authorisation should appear in a customer's account under the heading 'Authorisation Required' /account#/transactions

## Actual Behaviour

Historical complete transactions appear under the heading 'Authorisation Required' in users /account#/transactions

## Steps to Reproduce

I have looked at other accounts (mine and spree) and find the same thing: this does not just affect one user.

1.
2.
3.
4.

## Animated Gif/Screenshot

![authorations](https://user-images.githubusercontent.com/45104035/111474197-b5490a00-8723-11eb-83f4-b636fa4200f8.png)

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by andrewpbrett** [comment] 2021-06-16 15:48
This will likely be fixed once https://github.com/openfoodfoundation/openfoodnetwork/pull/7708 is merged

**Comment by RachL** [comment] 2021-07-22 09:02
@filipefurtad0 have you tested this scenario when testing #7708?

**Comment by filipefurtad0** [comment] 2021-07-22 15:12
Thanks for pointing this out @RachL - no, I have not checked for this scenario in the context of #7708...

For the first transaction of $1.83 on the `/transactions` table:
- order `number='R147666104'` -> `order_id=1437427` -> `payment_method_id=200157` which is `Spree::Gateway::StripeSCA`. The payment entry on the DB looks like this:

```
   id   | amount | order_id |         created_at         |         updated_at         | source_id |    source_type    | payment_method_id |   state   |        response_code        | avs_response | identifier | cvv_response_code | cvv_response_message 
--------+--------+----------+----------------------------+----------------------------+-----------+-------------------+-------------------+-----------+-----------------------------+--------------+------------+-------------------+----------------------
 321747 |   1.83 |  1437427 | 2020-11-23 12:30:36.75024  | 2020-11-23 12:30:39.262039 |     31889 | Spree::CreditCard |            200157 | completed | ch_1HqeBlFeu2q4nydcRBRUSAEq |              | UXFYGD2X   | M                 | CVV matches
```
payment `state = 'completed'`, but the link is still there. This order has actually five payments, and there is another one which is SCA as well. So this seems related (maybe a double) of #7601? I didn't notice this issue when opening this one.

I'll try to reproduce this in staging, now that we have #7708 merged.

**Comment by filipefurtad0** [comment] 2021-07-23 15:57
I think there might be some different several scenarios, which lead to some paid/complete orders with the respective payments still appearing on the `/account/transactions` of the customer... (some below). I'm not sure I reproduced this specific case, but even if such complete payments are not created anymore, I think we should keep this issue open as we might need to do a clean up of such "historical" payment intents... What do you think @andrewpbrett ?

Some related scenarios, which I think deserve dedicated issues (to be opened):

1)
i) adding an SCA payment in the BO
ii) cancelling the order; currently, the admin cannot cancel the previously added payment
iii) the SCA payment still appears in the `/account/transactions` of the customer; clicking on it will process the payment -> appears as `complete` on Stripe

2)
i) adding an SCA payment in the BO
ii) adding a second cash payment
iii) the SCA payment still appears in the `/account/transactions` of the customer; clicking on it will process the payment -> appears as `uncaptured` on Stripe (which means, it will get captured eventually, as recently discussed)

![image](https://user-images.githubusercontent.com/49817236/126806188-a0ac8b73-0f7c-43ea-b8b0-59d7f4242c07.png)

**Comment by andrewpbrett** [comment] 2021-08-14 00:52
As of #7708 the only payments that show up on that `/account/transactions` tab are those that are in the `requires_authorization` state. We no longer show payments in the `complete` state in that table, so I'm reasonably sure that, for example, the payment you mention in https://github.com/openfoodfoundation/wishlist/issues/5#issuecomment-884992800 @filipefurtad0 will no longer have the Authorize button next to it.

I think we can close this, but @filipefurtad0 if you feel strongly, or if @lbwright22 or @RachL has an example of an old payment that still has an Authorize button next to it, feel free to reopen.

**Closed by andrewpbrett** 2021-08-14 00:52 UTC
Labels: bug-s4, Potential Papercut

**Comment by filipefurtad0** [comment] 2021-08-16 11:31
Agree with closing here @andrewpbrett  :+1:
However, scenarios 1) and 2) still displays unnecessary payments on `/account/transactions`

1) I think this one is easy to work around, and does not really cause a bug:

![Peek 2021-08-16 12-24](https://user-images.githubusercontent.com/49817236/129556492-48c19700-6b73-4812-a56f-2e6b4e947857.gif)

Cancelling an order leaves the payment on `/account/transactions`; If the customer processes it, then the payment goes through, and the admin needs to issue a re-fund. Not really a bug, but it would be perhaps good that payments don't appear on the `/account/transactions` if the state of the order is `cancelled`.

2) If a second payment is added on top of SCA, and the order is complete, the payment authorization request still appears on the customers side. Clicking it leads to an error message, which is not ideal:

![Peek 2021-08-15 11-05](https://user-images.githubusercontent.com/49817236/129555786-000d8ce6-2239-45bc-a050-01d902362c91.gif)

The scope is different so creating separate S4 issues, as potential papercuts.

**Comment by filipefurtad0** [comment] 2021-08-16 14:33
Opened these two issues, for the respective scenarios:
1) https://github.com/openfoodfoundation/openfoodnetwork/issues/8057 (S4)
2) https://github.com/openfoodfoundation/openfoodnetwork/issues/8059 (S2)
