### ISSUE TITLE
[Shopfront] Don't display "from" when the producer is set to 'hide all references'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/wishlist#284] opened 2022-10-07 16:00 UTC
## What is the need / problem?
This is an outcome of testing [#9725](https://github.com/openfoodfoundation/openfoodnetwork/pull/9725)

If a producer's visibility is set to 'hide all references', it's name will not even be displayed below the product name in the shopfront. In that case we should also hide the string "from", because it is irritating to have it there on its own.

![image](https://user-images.githubusercontent.com/1790176/194597337-8101a6dc-af54-47fa-820e-b9a90247aba0.png)

## Which type of users does this problem affect (and how many, if known)?

- Shoppers

**Comment by drummer83** [comment] 2022-10-07 16:05
Or is this a bug?

**Comment by tschumilas** [comment] 2022-10-07 16:21
I previously asked if having the 'hide all references' apply within the shop front was a bug,  and the response was that this was intended.  There are some use cases where the shop does not want to identify the supplier in the shop.   (So its a way around our transparency really.)    So - I"d say we need to remove the 'from' as this issue suggests.

**Comment by RachL** [comment] 2022-10-07 21:20
@tschumilas this impact on the shopfront was not intended. That's why #9698 was opened. Our conversation was here https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1663724456458059?thread_ts=1663724456.458059&cid=CG7NJ966B

So I'm closing this one, but good catch @drummer83 !

**Closed** 2022-10-07 21:20 UTC
