### ISSUE TITLE
Allowing $0 adjustments to appear on an order's shipping notification, invoice and order confirmation emails

### ISSUE THREAD

**Issue by adele-ofn** [openfoodfoundation/wishlist#168] opened 2021-10-20 07:59 UTC
## What is the problem we are solving 
Unable to communicate specific information to customers in the shipping, invoice and order confirmation emails (automated by the system) - e.g. the shipment tracking number. It is suggested that allowing $0 adjustments to appear on communications sent to customers could provide a solution to this problem. 

When an adjustment is made to an order for $0, this adjustment appears in the shop's backoffice, but not in the shipping notification email (or other emails) sent to customers. If the $0 adjustment line could appear on these communications, it would present a very valuable method for communicating information to the customer.

![Screen Shot 2021-08-24 at 8 59 15 am](https://user-images.githubusercontent.com/89006237/138051951-91cc1574-ad1f-483d-8329-fae9748f1a28.png)

![Screen Shot 2021-08-24 at 9 00 40 am](https://user-images.githubusercontent.com/89006237/138051963-7e95908c-0ec6-4e29-a1ed-1281db3d803a.png)

## Success factors = expected outcome 
A $0 adjustment can be made in a shop's backoffice, and the text field can be used to input information relevant to that order (e.g. shipping number, change of pickup location). This $0 adjustment line will appear on automated communications sent to the customer.

## Useful information for inception
It has been suggested in global slack that this change may be a papercut.

**Comment by Matt-Yorkley** [comment] 2021-12-20 20:06
Sounds like a nice little feature (enable adding information to shipping, invoice and order confirmation emails), but I wouldn't recommend using $0 adjustments for this.

**Comment by jibees** [comment] 2022-03-02 13:19
Sounds like a Papercut confirmed, but needs to be product team approved.

**Comment by RachL** [comment] 2022-04-15 14:18
@lin-d-hop here I'm thinking going Matt's way: we add a "comment" section on the order, and the text can appear on the order. Needs some design, but does not look like something v. hard to do. We can put it for papercut review again once design is made. Thoughts?

**Comment by tschumilas** [comment] 2022-04-15 14:47
would it appear on all of:  customer order confirmation,  invoice,  and customer shipping confirmation email?   as well as in the back office on the order?

**Comment by RachL** [comment] 2022-04-19 16:02
@tschumilas to keep under papercut yes for  invoice and back office.

For emails I would handled that maybe in a second papercut: especially because we need to think about all the scenarios and the designs will be different. Like for example, because it is something you add on an order once the order has been created, I'm not sure how the customer can see it on the order confirmation. Unless you mean when you re-send the order confirmation?

![image](https://user-images.githubusercontent.com/6525576/164046671-236642d0-9119-4058-b7ca-658fc8eac1ba.png)

**Comment by tschumilas** [comment] 2022-04-19 17:28
I'm good with it on invoices and in the back office.  I just know we have some users who don't use invoices -  they re-send order confirmations.  But this is not a critical bit of work.....   if its on the invoice thats great.

**Comment by RachL** [comment] 2022-05-06 15:42
Some designs proposal : 

Currently there is a spot where you can add tracking numbers. I suggest we add the same type of bloc below it. Admins could write notes freely (maybe we need to limit the number of characters available). It could look like this (with the ability to edit and delete the note - whatever the order state?)

![image](https://user-images.githubusercontent.com/6525576/167166552-f64a5876-43d4-49c6-815d-e4d692dedc76.png)

On the invoice, we would add a section at the bottom, with same design than "payment summary" and "payment description at checkout". We will soon need to redesign completely our invoice so we don't print a forest each time we use them. But for the sake of the papercut, I think there is generally room to stick to the current design. Both invoices template have the same bottom info / behavior, e.g. : 

![image](https://user-images.githubusercontent.com/6525576/167165985-a2dd9d39-eb8e-4796-b0f5-f2344a7f839d.png)

with the title "additional information".

What do people think? If no strong opinion, I will rewrite the issue and move it to confirm papercuts.

**Comment by lin-d-hop** [comment] 2022-05-06 16:54
I think this will be useful and appreciated. Nice ideas @RachL Thanks!

**Comment by tschumilas** [comment] 2022-05-06 22:01
This looks good to me -  nice to follow the template of the payment description I think.  This would be very useful to the hubs I work with for sure.

**Comment by tschumilas** [comment] 2022-05-06 22:02
Thanks Rachel.

**Comment by RachL** [comment] 2022-05-11 09:46
Papercut review: we will do 2 papercuts out of this to be sure to ship them quickly: 1. Adding the note 2. generating invoices. And from there see if we do 3. Add the notes in email.

**Comment by RachL** [comment] 2022-05-12 15:57
Alright I've opened: 

https://github.com/openfoodfoundation/openfoodnetwork/issues/9178

and 

https://github.com/openfoodfoundation/openfoodnetwork/issues/9179

Closing here.

**Closed by RachL** 2022-05-12 15:57 UTC
Labels: enhancement, Potential Papercut
