### ISSUE TITLE
[Enterprise creation] Include the enterprise type choice in the registration process

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/wishlist#381] opened 2022-11-24 22:28 UTC
## What is the need / problem?
The first time users create an enterprise, they click the "Join" button on the homepage, go through the registration process (/register), and in the end are redirected to the welcome page where there is the enterprise type choice. [[But they can quit this page without selecting any enterprise type, by clicking on any button or quitting the page --> actually they can quit but will still have the selection to make when they come back. ]]

Furthermore, if a user who already has an enterprise clicks on "Join" button on the homepage for the second time, at the end of the registration process they will not land on the welcome page and not be asked to choose any enterprise type.  

## Which type of users does this problem affect (and how many, if known)?
_- Hub Managers (MCFEs)_
_- Producers_

## Potential solutions that will solve the problem  ?[[brainstorming to list feature candidates]
Include the enterprise type choice in the registration process wizard. In the end of the registration process, the "Go to the admin dashboard" redirects to the admin dashboard instead of the welcome page -  same than for a "second" registration. 

### After creating your 1st enterprise you land on this page, that you can quit without selecting an enterprise type
![Screen Shot 2022-11-24 at 23 06 06](https://user-images.githubusercontent.com/28386648/203869316-312b45a2-34da-4235-b8f0-b9aa2d084adf.png)

### Process when you create your 2nd enterprise: no welcome page anymore, no enterprise choice
![Nice process](https://user-images.githubusercontent.com/28386648/203870280-81bb9253-60b5-4def-b029-bee333790758.gif)

### Some enterprises just created by users: they don't have any type selected
![Screen Shot 2022-11-24 at 23 00 09](https://user-images.githubusercontent.com/28386648/203870009-e0cf7142-3aac-492c-897f-0db41798e9a0.png)
![Screen Shot 2022-11-24 at 23 00 04](https://user-images.githubusercontent.com/28386648/203870010-f08478fc-3119-4632-a519-3942f6d78ce8.png)
![Screen Shot 2022-11-24 at 22 59 53](https://user-images.githubusercontent.com/28386648/203870012-be05de06-26c3-4619-8d50-878313b633f8.png)

**Comment by RachL** [comment] 2022-11-30 15:27
Duplicate of: https://github.com/openfoodfoundation/wishlist/issues/286 if I'm not mistaken.

**Closed by RachL** 2022-11-30 15:27 UTC
