### ISSUE TITLE
Possible new category name option for enterprise fees

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/wishlist#75] opened 2021-07-21 17:24 UTC
## What is the need / problem?

I have a large UK user who would like an extra option for naming their enterprise fees. It is something that I imagine might be of use to other hubs.

The user would like ‘Membership fee’ added as a name. They use the flat rate per order enterprise fee on order cycles open to the public. On completion of their first order the customer is hence automatically charged for membership and can be moved onto the hub customer list (and hence access the private shop front for future orders).

They currently call this enterprise fee ‘admin’ (the options are transport, packing, admin, fundraising, sales). Customers find ‘admin’ confusing on their invoices.

I imagine other enterprises may use the same system to collect members and membership fees and so I think the addition would help more than one hub.

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_

## Connected wishlist and discovery discussions* [list precedent discussions]

Migrated from Discourse:
https://community.openfoodnetwork.org/t/possible-new-category-name-option-for-enterprise-fees/1770

Originally opened
By: lbwright22
When: Oct '19

## Is Papercut or feature candidate?

Papercut Candidate

**Comment by jaycmb** [comment] 2021-08-25 13:11
I d assume this is **papercut size** from product input and no design input needed

> I imagine other enterprises may use the same system to collect members and membership fees and so I think the addition would help more than one hub.

-> Need to validated if this is a common use case indeed.

Do customers find the Fee Type or the Fee Name on the Invoice?
An option could also be do print the _Name_ on the invoice, so users can customize what their customers see on the invoice. That´ll be more than Paper Cut though I assume
<img width="743" alt="image" src="https://user-images.githubusercontent.com/39744592/130796350-eb533b4e-2d5d-4b9e-9ed2-8a1417f38152.png">

**Comment by RachL** [comment] 2021-09-08 15:52
@jaycmb I think this suggestion is close / almost a duplicate of to https://github.com/openfoodfoundation/wishlist/issues/126 but there are 2 different solutions. I like the idea of using fee names only and not fee types to avoid having to manage types. But we might need to restrict the size of the name.

**Comment by jaycmb** [comment] 2021-09-08 16:28
Papercut Meeting Sept 8th

Confirmed to be Papercut from tech side to swap Enterprise name and type.
Restriction for the input length of the name field is needed,
like 20 characters **(to be verified for mobile)**.

**Comment by RachL** [comment] 2021-09-09 09:57
@jaycmb I've moved https://github.com/openfoodfoundation/wishlist/issues/126 to confirmed papercut, and I will close this one.

If the papercut gets pick up, we will need to write nice acceptance criteria for it in the OFN main repo. Maybe something we should do for all papercut that have followed the wishlist repo?

**Closed by RachL** 2021-09-09 09:57 UTC
Labels: Potential Papercut, Admin Experience, A 1.Shop/Hub Administration

**Comment by jaycmb** [comment] 2021-09-09 11:32
> Maybe something we should do for all papercut that have followed the wishlist repo?

By _that have followed the wishlist repo_ you mean that made it proceeded from wishlist repo to man repo?
Or that flow along the wishlist repo from _potential_ to _confirmed_?

However, agree that the latest when a papercut makes it into main repo it should have clear AC.
Maybe even for being voted on, so that the scope is clear for everyone?
